# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#development:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: crowd_surf_development
#  pool: 5
#  username: root
#  password:
development:
  adapter: postgresql
  encoding: utf8
  database: crowd_surf_development
  username: postgres
  password: adminstpl
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: crowd_surf_development
  username: postgres
  password: adminstpl
  host: localhost
